schema_version: v0.0.1

environment:
  import: ./env.yml

application:
  import: ./app.yml

deployment:
  name: wordpressDeployment
  description: Wordpress Deployment
  deploymentConfig:
    artifact:
      id: 1435bc98-bea6-11eb-8529-0242ac130003
    provisioner: aws
    template:
      moduleRefId: aws:basic-eks-regional@1
      inputs:
        cluster: "$cluster"
        region:  "$region"
        roleArn:  "$roleArn"
        ports:
          -  name: "wordpress"
             containerPort: 80
             protocol": "TCP"
    env:
      cluster: "${terraform.cluster_name.value}"
      region: "${terraform.cluster_region.value}"
      roleArn: "${terraform.eks_arn.value}"
      PG_HOST: "${terraform.rds_instance_address.value}"
      REDIS_HOST: "${terraform.redis_hostname.value}"
    summary:
      - name: Service URL
        command: sleep 10 ; echo http://`kubectl get ingress -n wordpress-app -o=jsonpath={.items[*].status.loadBalancer.ingress[*].hostname}`